# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/meital/clion-2020.1.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/meital/clion-2020.1.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/meital/ObliviousDictionary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/meital/ObliviousDictionary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/meital/clion-2020.1.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/meital/clion-2020.1.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ObliviousDictionary/CMakeFiles /home/meital/ObliviousDictionary/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/meital/ObliviousDictionary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named obliviousDictionary

# Build rule for target.
obliviousDictionary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 obliviousDictionary
.PHONY : obliviousDictionary

# fast build rule for target.
obliviousDictionary/fast:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/build
.PHONY : obliviousDictionary/fast

Hasher.o: Hasher.cpp.o

.PHONY : Hasher.o

# target to build an object file
Hasher.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Hasher.cpp.o
.PHONY : Hasher.cpp.o

Hasher.i: Hasher.cpp.i

.PHONY : Hasher.i

# target to preprocess a source file
Hasher.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Hasher.cpp.i
.PHONY : Hasher.cpp.i

Hasher.s: Hasher.cpp.s

.PHONY : Hasher.s

# target to generate assembly for a file
Hasher.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Hasher.cpp.s
.PHONY : Hasher.cpp.s

ObliviousDictionary.o: ObliviousDictionary.cpp.o

.PHONY : ObliviousDictionary.o

# target to build an object file
ObliviousDictionary.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ObliviousDictionary.cpp.o
.PHONY : ObliviousDictionary.cpp.o

ObliviousDictionary.i: ObliviousDictionary.cpp.i

.PHONY : ObliviousDictionary.i

# target to preprocess a source file
ObliviousDictionary.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ObliviousDictionary.cpp.i
.PHONY : ObliviousDictionary.cpp.i

ObliviousDictionary.s: ObliviousDictionary.cpp.s

.PHONY : ObliviousDictionary.s

# target to generate assembly for a file
ObliviousDictionary.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ObliviousDictionary.cpp.s
.PHONY : ObliviousDictionary.cpp.s

Poly.o: Poly.cpp.o

.PHONY : Poly.o

# target to build an object file
Poly.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Poly.cpp.o
.PHONY : Poly.cpp.o

Poly.i: Poly.cpp.i

.PHONY : Poly.i

# target to preprocess a source file
Poly.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Poly.cpp.i
.PHONY : Poly.cpp.i

Poly.s: Poly.cpp.s

.PHONY : Poly.s

# target to generate assembly for a file
Poly.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Poly.cpp.s
.PHONY : Poly.cpp.s

ProtocolParty.o: ProtocolParty.cpp.o

.PHONY : ProtocolParty.o

# target to build an object file
ProtocolParty.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ProtocolParty.cpp.o
.PHONY : ProtocolParty.cpp.o

ProtocolParty.i: ProtocolParty.cpp.i

.PHONY : ProtocolParty.i

# target to preprocess a source file
ProtocolParty.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ProtocolParty.cpp.i
.PHONY : ProtocolParty.cpp.i

ProtocolParty.s: ProtocolParty.cpp.s

.PHONY : ProtocolParty.s

# target to generate assembly for a file
ProtocolParty.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/ProtocolParty.cpp.s
.PHONY : ProtocolParty.cpp.s

Tools.o: Tools.cpp.o

.PHONY : Tools.o

# target to build an object file
Tools.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Tools.cpp.o
.PHONY : Tools.cpp.o

Tools.i: Tools.cpp.i

.PHONY : Tools.i

# target to preprocess a source file
Tools.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Tools.cpp.i
.PHONY : Tools.cpp.i

Tools.s: Tools.cpp.s

.PHONY : Tools.s

# target to generate assembly for a file
Tools.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/Tools.cpp.s
.PHONY : Tools.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/obliviousDictionary.dir/build.make CMakeFiles/obliviousDictionary.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... obliviousDictionary"
	@echo "... Hasher.o"
	@echo "... Hasher.i"
	@echo "... Hasher.s"
	@echo "... ObliviousDictionary.o"
	@echo "... ObliviousDictionary.i"
	@echo "... ObliviousDictionary.s"
	@echo "... Poly.o"
	@echo "... Poly.i"
	@echo "... Poly.s"
	@echo "... ProtocolParty.o"
	@echo "... ProtocolParty.i"
	@echo "... ProtocolParty.s"
	@echo "... Tools.o"
	@echo "... Tools.i"
	@echo "... Tools.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

